{"comments": {}, "bugs": {"647722": {"comments": [{"bug_id": 647722, "count": 0, "time": "2011-04-04T18:35:17Z", "creator": "kaie@kuix.de", "author": "kaie@kuix.de", "raw_text": "My experimental PSM code that uses CERT_PKIXVerifyCert fails.\n\nIn order to find a simple test case, I used https://wiki.mozilla.org\n(With the cert from that site the pkix debug logs aren't getting as big as for most other sites)\n\nI'l attach a log file.\n(I enabled debugging #define in pkix_build.c\n\n\nFailure is PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED\n\n\n$7 = {errCode = PKIX_BUILDINITIATEBUILDCHAINFAILED, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c6a0, info = 0x0}\n(gdb) print *error->cause\n$8 = {errCode = PKIX_UNABLETOBUILDCHAIN, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c7a0, info = 0x0}\n(gdb) print *error->cause->cause\n$9 = {errCode = PKIX_BUILDFORWARDDEPTHFIRSTSEARCHFAILED, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c3a0, info = 0x0}\n(gdb) print *error->cause->cause->cause\n$10 = {errCode = PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED, errClass = PKIX_BUILD_ERROR, plErr = 4294959124, cause = 0x0, info = 0x0}", "is_private": false, "tags": [], "creation_time": "2011-04-04T18:35:17Z", "attachment_id": null, "id": 5390357, "text": "My experimental PSM code that uses CERT_PKIXVerifyCert fails.\n\nIn order to find a simple test case, I used https://wiki.mozilla.org\n(With the cert from that site the pkix debug logs aren't getting as big as for most other sites)\n\nI'l attach a log file.\n(I enabled debugging #define in pkix_build.c\n\n\nFailure is PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED\n\n\n$7 = {errCode = PKIX_BUILDINITIATEBUILDCHAINFAILED, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c6a0, info = 0x0}\n(gdb) print *error->cause\n$8 = {errCode = PKIX_UNABLETOBUILDCHAIN, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c7a0, info = 0x0}\n(gdb) print *error->cause->cause\n$9 = {errCode = PKIX_BUILDFORWARDDEPTHFIRSTSEARCHFAILED, errClass = PKIX_BUILD_ERROR, plErr = 0, cause = 0xa3b8c3a0, info = 0x0}\n(gdb) print *error->cause->cause->cause\n$10 = {errCode = PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED, errClass = PKIX_BUILD_ERROR, plErr = 4294959124, cause = 0x0, info = 0x0}"}, {"tags": [], "is_private": false, "time": "2011-04-04T18:37:11Z", "count": 1, "bug_id": 647722, "raw_text": "", "author": "kaie@kuix.de", "text": "Created attachment 523997\nlogfile", "creator": "kaie@kuix.de", "id": 5390358, "attachment_id": 523997, "creation_time": "2011-04-04T18:37:11Z"}, {"time": "2011-04-04T22:29:24Z", "bug_id": 647722, "count": 2, "creator": "kaie@kuix.de", "author": "kaie@kuix.de", "tags": [], "is_private": false, "raw_text": "bug still exists with tip of NSS, as of today.", "text": "bug still exists with tip of NSS, as of today.", "id": 5390561, "attachment_id": null, "creation_time": "2011-04-04T22:29:24Z"}, {"author": "kaie@kuix.de", "creator": "kaie@kuix.de", "time": "2011-04-04T23:30:06Z", "count": 3, "bug_id": 647722, "id": 5390609, "attachment_id": null, "text": "I would expect that PKIX_PL_Cert_IsCertTrusted(builtin-root) returns true.\nHowever, for the root CA in this scenario, this function returns not-trusted.\n\nThe issue might be inside pkix_pl_Pk11CertStore_CheckTrust\n\nThe SSL client code passes cert-usage certUsageSSLClient,\nand pkix concludes that it needs trust bits 128,\nbut it has 24, so it fails.", "creation_time": "2011-04-04T23:30:06Z", "is_private": false, "tags": [], "raw_text": "I would expect that PKIX_PL_Cert_IsCertTrusted(builtin-root) returns true.\nHowever, for the root CA in this scenario, this function returns not-trusted.\n\nThe issue might be inside pkix_pl_Pk11CertStore_CheckTrust\n\nThe SSL client code passes cert-usage certUsageSSLClient,\nand pkix concludes that it needs trust bits 128,\nbut it has 24, so it fails."}, {"author": "kaie@kuix.de", "creator": "kaie@kuix.de", "count": 4, "bug_id": 647722, "time": "2011-04-05T01:26:48Z", "creation_time": "2011-04-05T01:26:48Z", "attachment_id": null, "id": 5390710, "text": "oh... SECCertUsage != SECCertificateUsage", "raw_text": "oh... SECCertUsage != SECCertificateUsage", "is_private": false, "tags": []}, {"author": "kaie@kuix.de", "creator": "kaie@kuix.de", "text": "I think this bug is invalid.\nMy mistake.\nI used the wrong cert usage constants...", "attachment_id": null, "id": 5390716, "creation_time": "2011-04-05T01:42:19Z", "tags": [], "is_private": false, "time": "2011-04-05T01:42:19Z", "count": 5, "bug_id": 647722, "raw_text": "I think this bug is invalid.\nMy mistake.\nI used the wrong cert usage constants..."}, {"author": "wtc@google.com", "creator": "wtc@google.com", "time": "2011-04-06T22:49:29Z", "count": 6, "bug_id": 647722, "text": "Kai: I also ran into this bug last week, so I think it\nis worth getting to the bottom of this bug.\n\nAs an experiment, I passed certificateUsageSSLClient instead\nof certificateUsageSSLServer, as an experiment.  I was\nexpecting to get the SEC_ERROR_INADEQUATE_KEY_USAGE error.\nBut I was surprised to get SEC_ERROR_UNTRUSTED_ISSUER, caused\nby PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED.\n\nNote that certificateUsageSSLClient is a valid SECCertificateUsage\nvalue.  But even with an invalid cert usage constant, isn't it\nstrange that it causes libpkix to build a certification loop?", "attachment_id": null, "id": 5393440, "creation_time": "2011-04-06T22:49:29Z", "tags": [], "is_private": false, "raw_text": "Kai: I also ran into this bug last week, so I think it\nis worth getting to the bottom of this bug.\n\nAs an experiment, I passed certificateUsageSSLClient instead\nof certificateUsageSSLServer, as an experiment.  I was\nexpecting to get the SEC_ERROR_INADEQUATE_KEY_USAGE error.\nBut I was surprised to get SEC_ERROR_UNTRUSTED_ISSUER, caused\nby PKIX_LOOPDISCOVEREDDUPCERTSNOTALLOWED.\n\nNote that certificateUsageSSLClient is a valid SECCertificateUsage\nvalue.  But even with an invalid cert usage constant, isn't it\nstrange that it causes libpkix to build a certification loop?"}, {"author": "kaie@kuix.de", "creator": "kaie@kuix.de", "count": 7, "bug_id": 647722, "time": "2011-04-06T22:55:14Z", "creation_time": "2011-04-06T22:55:14Z", "text": "(In reply to comment #6)\n> But even with an invalid cert usage constant, isn't it\n> strange that it causes libpkix to build a certification loop?\n\nagreed", "id": 5393449, "attachment_id": null, "raw_text": "(In reply to comment #6)\n> But even with an invalid cert usage constant, isn't it\n> strange that it causes libpkix to build a certification loop?\n\nagreed", "tags": [], "is_private": false}, {"raw_text": "Kai: did you pass certUsageSSLServer as the SECCertificateUsage\nargument?  certUsageSSLServer has the same value as\ncertificateUsageSSLClient, so you actually ran into the exact\nsame problem as I did.", "bug_id": 647722, "count": 8, "time": "2011-04-06T23:21:09Z", "is_private": false, "tags": [], "creation_time": "2011-04-06T23:21:09Z", "attachment_id": null, "id": 5393504, "creator": "wtc@google.com", "text": "Kai: did you pass certUsageSSLServer as the SECCertificateUsage\nargument?  certUsageSSLServer has the same value as\ncertificateUsageSSLClient, so you actually ran into the exact\nsame problem as I did.", "author": "wtc@google.com"}, {"time": "2011-04-06T23:26:19Z", "count": 9, "bug_id": 647722, "author": "kaie@kuix.de", "creator": "kaie@kuix.de", "tags": [], "is_private": false, "raw_text": "(In reply to comment #8)\n> Kai: did you pass certUsageSSLServer as the SECCertificateUsage\n> argument?\n\nYes, that's exactly what I did.", "text": "(In reply to comment #8)\n> Kai: did you pass certUsageSSLServer as the SECCertificateUsage\n> argument?\n\nYes, that's exactly what I did.", "id": 5393514, "attachment_id": null, "creation_time": "2011-04-06T23:26:19Z"}]}}}