{"bugs": {"642031": {"comments": [{"attachment_id": null, "author": "philipp@weitershausen.de", "is_private": false, "creation_time": "2011-03-16T00:47:19Z", "text": "The crappy wifi at SFO redirects me back to the captive portal after a while of browsing the interwebs. If a sync is happening in the period before I unlock it again by clicking the Whatever button in the captive portal, it errors with an Unkonwn Error. Excerpt from log:\n\n1300236063004\tService.Main\tINFO\tStarting sync at 2011-03-15 17:41:03\n1300236063004\tService.Main\tINFO\tIn sync().\n1300236063004\tService.Main\tDEBUG\tClearing sync triggers.\n1300236165463\tNet.Resource\tDEBUG\tGET success 200 https://phx-sync091.services.mozilla.com/1.0/philikon/info/collections\n1300236165477\tService.Main\tDEBUG\tException: info.obj is null JS Stack trace: ()@service.js:1746 < WrappedNotify()@util.js:172 < WrappedLock()@util.js:140 < _lockedSync()@service.js:1695 < ()@service.js:1686 < WrappedCatch()@util.js:114 < sync(false)@service.js:1667 < ([object Object])@service.js:596 < notify([object XPCWrappedNative_NoHelper])@util.js:1185\n\nThis should be reported as a network error so that our error reporting stuff knows how to deal with it.", "id": 5347308, "raw_text": "The crappy wifi at SFO redirects me back to the captive portal after a while of browsing the interwebs. If a sync is happening in the period before I unlock it again by clicking the Whatever button in the captive portal, it errors with an Unkonwn Error. Excerpt from log:\n\n1300236063004\tService.Main\tINFO\tStarting sync at 2011-03-15 17:41:03\n1300236063004\tService.Main\tINFO\tIn sync().\n1300236063004\tService.Main\tDEBUG\tClearing sync triggers.\n1300236165463\tNet.Resource\tDEBUG\tGET success 200 https://phx-sync091.services.mozilla.com/1.0/philikon/info/collections\n1300236165477\tService.Main\tDEBUG\tException: info.obj is null JS Stack trace: ()@service.js:1746 < WrappedNotify()@util.js:172 < WrappedLock()@util.js:140 < _lockedSync()@service.js:1695 < ()@service.js:1686 < WrappedCatch()@util.js:114 < sync(false)@service.js:1667 < ([object Object])@service.js:596 < notify([object XPCWrappedNative_NoHelper])@util.js:1185\n\nThis should be reported as a network error so that our error reporting stuff knows how to deal with it.", "count": 0, "tags": [], "creator": "philipp@weitershausen.de", "time": "2011-03-16T00:47:19Z", "bug_id": 642031}, {"author": "bugzilla@twinql.com", "creation_time": "2011-03-16T02:27:31Z", "text": "We've seen \"info.obj is null\" at very infrequent intervals for as long as I've been working on Sync... including at the Mountain View office, and at home. (You might recall a n00b named Richard putting a workaround in one of his first patches!)\n\nIt thus cannot be just a captive portal issue, though that might be the easiest way to prompt the error.\n\nA good solution should spot this condition inside Resource, rather than returning a valid-but-broken response -- info.obj being lazy.\n\nWe should also check that we're checking all of the necessary success flags when we fetch info/collections; I'm not sure we do.\n\nFinally, it might be worthwhile revisiting Bug 623080...", "id": 5347466, "raw_text": "We've seen \"info.obj is null\" at very infrequent intervals for as long as I've been working on Sync... including at the Mountain View office, and at home. (You might recall a n00b named Richard putting a workaround in one of his first patches!)\n\nIt thus cannot be just a captive portal issue, though that might be the easiest way to prompt the error.\n\nA good solution should spot this condition inside Resource, rather than returning a valid-but-broken response -- info.obj being lazy.\n\nWe should also check that we're checking all of the necessary success flags when we fetch info/collections; I'm not sure we do.\n\nFinally, it might be worthwhile revisiting Bug 623080...", "count": 1, "tags": [], "creator": "bugzilla@twinql.com", "bug_id": 642031, "attachment_id": null, "is_private": false, "time": "2011-03-16T02:27:31Z"}, {"author": "bugzilla@twinql.com", "creation_time": "2011-03-25T06:44:13Z", "text": "See also: Bug 587956.", "id": 5368568, "raw_text": "See also: Bug 587956.", "count": 2, "creator": "bugzilla@twinql.com", "tags": [], "bug_id": 642031, "attachment_id": null, "is_private": false, "time": "2011-03-25T06:44:13Z"}]}}, "comments": {}}