{"bugs": {"701524": {"comments": [{"id": 5841365, "is_private": false, "count": 0, "tags": [], "bug_id": 701524, "creation_time": "2011-11-10T22:16:17Z", "raw_text": "Now that we have the android logcat appended to the end of test logs, its become apparent that the SUT agent is quite noisy in the log. There are frequent FileNotFoundExceptions even on green runs. My concern is that these spurious exceptions will make it harder for us to find real issues on failed tests.", "attachment_id": null, "time": "2011-11-10T22:16:17Z", "text": "Now that we have the android logcat appended to the end of test logs, its become apparent that the SUT agent is quite noisy in the log. There are frequent FileNotFoundExceptions even on green runs. My concern is that these spurious exceptions will make it harder for us to find real issues on failed tests.", "author": "lassey@chromium.org", "creator": "lassey@chromium.org"}, {"creator": "bmoss@mozilla.com", "author": "bmoss@mozilla.com", "text": "I'm guessing that this is a result of the python code checking for the existence of a file before pushing a file, or some other such usage. I'm not sure changing the Agent is the correct solution. Do you have specifics on your concern?", "attachment_id": null, "time": "2011-11-10T23:04:21Z", "creation_time": "2011-11-10T23:04:21Z", "raw_text": "I'm guessing that this is a result of the python code checking for the existence of a file before pushing a file, or some other such usage. I'm not sure changing the Agent is the correct solution. Do you have specifics on your concern?", "bug_id": 701524, "count": 1, "is_private": false, "tags": [], "id": 5841525}, {"creator": "lassey@chromium.org", "author": "lassey@chromium.org", "count": 2, "is_private": false, "tags": [], "id": 5841568, "bug_id": 701524, "creation_time": "2011-11-10T23:15:15Z", "raw_text": "in normal usage, the java code really shouldn't be throwing exceptions. In the case of the file not found exceptions, just call file.exists() before any file operations that would require it to exist.", "text": "in normal usage, the java code really shouldn't be throwing exceptions. In the case of the file not found exceptions, just call file.exists() before any file operations that would require it to exist.", "attachment_id": null, "time": "2011-11-10T23:15:15Z"}, {"creator": "jmaher@mozilla.com", "author": "jmaher@mozilla.com", "creation_time": "2011-11-11T11:33:15Z", "raw_text": "on a side note, I think our data collected from logcat in the tinderbox logs is not very useful.", "text": "on a side note, I think our data collected from logcat in the tinderbox logs is not very useful.", "time": "2011-11-11T11:33:15Z", "attachment_id": null, "tags": [], "count": 3, "is_private": false, "id": 5842425, "bug_id": 701524}]}}, "comments": {}}