{"bugs": {"631846": {"comments": [{"is_private": false, "tags": [], "raw_text": "While doing QA, I was trying to access a deleted attachment. An error was thrown telling me that the attachment was gone (as expected), but my credentials looked like they were gone (no saved searches in the footer, no login name in the banner either). That's because attachment.cgi first redirected me to the alternate host, then threw the error. We should enforce Bugzilla::Error::_throw_error() to throw errors from the main urlbase, to avoid such confusion.", "creation_time": "2011-02-05T22:17:31Z", "bug_id": 631846, "id": 5257998, "time": "2011-02-05T22:17:31Z", "attachment_id": null, "creator": "LpSolit@gmail.com", "author": "LpSolit@gmail.com", "count": 0, "text": "While doing QA, I was trying to access a deleted attachment. An error was thrown telling me that the attachment was gone (as expected), but my credentials looked like they were gone (no saved searches in the footer, no login name in the banner either). That's because attachment.cgi first redirected me to the alternate host, then threw the error. We should enforce Bugzilla::Error::_throw_error() to throw errors from the main urlbase, to avoid such confusion."}, {"creation_time": "2011-02-06T06:31:30Z", "bug_id": 631846, "raw_text": "Ah, well, we can't exactly do that, but we it would probably be better to do some sort of check before the redirect that would avoid this specific case. Otherwise, it seems like you're saying one of two things:\n\n(a) Redirect to a special \"error page\" that we would create just for this purpose (which seems like a lot of complexity to just handle this one small issue).\n\n(b) Throw an error about not being able to throw an error (which would be kind of silly).", "tags": [], "is_private": false, "time": "2011-02-06T06:31:30Z", "id": 5258340, "creator": "mkanat@bugzilla.org", "attachment_id": null, "count": 1, "text": "Ah, well, we can't exactly do that, but we it would probably be better to do some sort of check before the redirect that would avoid this specific case. Otherwise, it seems like you're saying one of two things:\n\n(a) Redirect to a special \"error page\" that we would create just for this purpose (which seems like a lot of complexity to just handle this one small issue).\n\n(b) Throw an error about not being able to throw an error (which would be kind of silly).", "author": "mkanat@bugzilla.org"}, {"author": "LpSolit@gmail.com", "text": "I mean neither (a) nor (b). Maybe should I simply fix attachment.cgi to first validate the attachment ID and data before redirecting to the alternate host. We will see.", "count": 2, "attachment_id": null, "creator": "LpSolit@gmail.com", "id": 5258414, "time": "2011-02-06T09:56:50Z", "is_private": false, "tags": [], "raw_text": "I mean neither (a) nor (b). Maybe should I simply fix attachment.cgi to first validate the attachment ID and data before redirecting to the alternate host. We will see.", "creation_time": "2011-02-06T09:56:50Z", "bug_id": 631846}, {"time": "2011-02-07T07:50:57Z", "id": 5259600, "is_private": false, "bug_id": 631846, "creation_time": "2011-02-07T07:50:57Z", "raw_text": "(In reply to comment #2)\n> Maybe should I simply fix attachment.cgi to first\n> validate the attachment ID and data before redirecting to the alternate host.\n\n  Oh cool. That sounds sensible.", "tags": [], "author": "mkanat@bugzilla.org", "text": "(In reply to comment #2)\n> Maybe should I simply fix attachment.cgi to first\n> validate the attachment ID and data before redirecting to the alternate host.\n\n  Oh cool. That sounds sensible.", "count": 3, "attachment_id": null, "creator": "mkanat@bugzilla.org"}, {"creator": "LpSolit@gmail.com", "attachment_id": null, "text": "*** Bug 945966 has been marked as a duplicate of this bug. ***", "count": 4, "author": "LpSolit@gmail.com", "bug_id": 631846, "creation_time": "2013-12-03T23:25:36Z", "raw_text": "", "tags": [], "is_private": false, "time": "2013-12-03T23:25:36Z", "id": 8151630}]}}, "comments": {}}