{"bugs": {"1641315": {"comments": [{"creation_time": "2020-05-27T18:55:20Z", "creator": "bugzilla@dblohm7.ca", "attachment_id": null, "text": "This bug is for crash report bp-3eeace59-6ef5-47a1-b024-181750200526.\n\n```\nJava stack trace:\n\njava.lang.IllegalStateException\n\tat org.mozilla.gecko.process.GeckoProcessManager$ChildConnection.getPid(GeckoProcessManager.java:4)\n\tat org.mozilla.gecko.process.GeckoProcessManager$ConnectionManager.removeContentConnection(GeckoProcessManager.java:3)\n\tat org.mozilla.gecko.process.GeckoProcessManager$ConnectionManager.removeConnection(GeckoProcessManager.java:4)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.unbindService(ServiceAllocator.java:16)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.onBinderConnectedInternal(ServiceAllocator.java:15)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo$Binding.lambda$onServiceConnected$0$ServiceAllocator$InstanceInfo$Binding(ServiceAllocator.java:2)\n\tat org.mozilla.gecko.process.-$$Lambda$ServiceAllocator$InstanceInfo$Binding$GH4LBN9B7GpQKa5rjxdu9sMiy1s.run(Unknown Source:4)\n\tat org.mozilla.gecko.util.XPCOMEventTarget.runOnLauncherThread(XPCOMEventTarget.java:3)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo$Binding.onServiceConnected(ServiceAllocator.java:1)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1963)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1995)\n\tat org.mozilla.gecko.util.XPCOMEventTarget$JNIRunnable.run(XPCOMEventTarget.java:1)\n\n```", "id": 14847042, "raw_text": "This bug is for crash report bp-3eeace59-6ef5-47a1-b024-181750200526.\n\n```\nJava stack trace:\n\njava.lang.IllegalStateException\n\tat org.mozilla.gecko.process.GeckoProcessManager$ChildConnection.getPid(GeckoProcessManager.java:4)\n\tat org.mozilla.gecko.process.GeckoProcessManager$ConnectionManager.removeContentConnection(GeckoProcessManager.java:3)\n\tat org.mozilla.gecko.process.GeckoProcessManager$ConnectionManager.removeConnection(GeckoProcessManager.java:4)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.unbindService(ServiceAllocator.java:16)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.onBinderConnectedInternal(ServiceAllocator.java:15)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo$Binding.lambda$onServiceConnected$0$ServiceAllocator$InstanceInfo$Binding(ServiceAllocator.java:2)\n\tat org.mozilla.gecko.process.-$$Lambda$ServiceAllocator$InstanceInfo$Binding$GH4LBN9B7GpQKa5rjxdu9sMiy1s.run(Unknown Source:4)\n\tat org.mozilla.gecko.util.XPCOMEventTarget.runOnLauncherThread(XPCOMEventTarget.java:3)\n\tat org.mozilla.gecko.process.ServiceAllocator$InstanceInfo$Binding.onServiceConnected(ServiceAllocator.java:1)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1963)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1995)\n\tat org.mozilla.gecko.util.XPCOMEventTarget$JNIRunnable.run(XPCOMEventTarget.java:1)\n\n```", "time": "2020-05-27T18:55:20Z", "author": "bugzilla@dblohm7.ca", "is_private": false, "count": 0, "tags": [], "bug_id": 1641315}, {"raw_text": "\nThis crash hits when a `RemoteException` is thrown during `onServiceConnected`.\nWe `unbind`, which destroys all our bookkeeping data. During this destruction,\nwe also attempt to retrieve the pid, which fails because we lost our binding\nbefore we had a chance to retrieve it.\n\nThis patch adds a new exception to be thrown in this case, which we explicitly\ncatch in `removeContentConnection`.", "time": "2020-05-27T19:25:04Z", "author": "bugzilla@dblohm7.ca", "tags": [], "bug_id": 1641315, "count": 1, "is_private": false, "creation_time": "2020-05-27T19:25:04Z", "creator": "bugzilla@dblohm7.ca", "attachment_id": 9152186, "text": "Created attachment 9152186\nBug 1641315: Fix crash when a binding connection is lost during final connection setup; r=#geckoview-reviewers\n\n\nThis crash hits when a `RemoteException` is thrown during `onServiceConnected`.\nWe `unbind`, which destroys all our bookkeeping data. During this destruction,\nwe also attempt to retrieve the pid, which fails because we lost our binding\nbefore we had a chance to retrieve it.\n\nThis patch adds a new exception to be thrown in this case, which we explicitly\ncatch in `removeContentConnection`.", "id": 14847089}, {"author": "pulsebot@bots.tld", "id": 14848291, "text": "Pushed by aklotz@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/18c2608ab71f\nFix crash when a binding connection is lost during final connection setup; r=geckoview-reviewers,agi", "tags": [], "bug_id": 1641315, "count": 2, "is_private": false, "creation_time": "2020-05-27T23:09:17Z", "raw_text": "Pushed by aklotz@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/18c2608ab71f\nFix crash when a binding connection is lost during final connection setup; r=geckoview-reviewers,agi", "time": "2020-05-27T23:09:17Z", "creator": "pulsebot@bots.tld", "attachment_id": null}, {"author": "nerli@mozilla.com", "count": 3, "is_private": false, "bug_id": 1641315, "tags": ["bugherder"], "raw_text": "https://hg.mozilla.org/mozilla-central/rev/18c2608ab71f", "time": "2020-05-28T15:56:09Z", "text": "https://hg.mozilla.org/mozilla-central/rev/18c2608ab71f", "id": 14849713, "creation_time": "2020-05-28T15:56:09Z", "attachment_id": null, "creator": "nerli@mozilla.com"}]}}, "comments": {}}