{"comments": {}, "bugs": {"1615412": {"comments": [{"raw_text": "STR:\n\n1. Launch the Browser Toolbox\n\nER:\n\nThe Browser Toolbox should attach.\n\nAR:\n\nThe Browser Toolbox shows a \"Browser Toolbox connection status\" error message. See screenshot (I can't seem to cut and paste the error text, frustratingly).\n\nSometimes when I see this error, I can restart the Browser Toolbox, and it attaches properly. This time, however, no matter how many times I restart the Browser Toolbox, it shows me the same error message.", "time": "2020-02-13T19:23:12Z", "author": "mconley@mozilla.com", "count": 0, "is_private": false, "bug_id": 1615412, "tags": [], "creation_time": "2020-02-13T19:23:12Z", "creator": "mconley@mozilla.com", "attachment_id": 9126511, "id": 14640004, "text": "Created attachment 9126511\nimage.png\n\nSTR:\n\n1. Launch the Browser Toolbox\n\nER:\n\nThe Browser Toolbox should attach.\n\nAR:\n\nThe Browser Toolbox shows a \"Browser Toolbox connection status\" error message. See screenshot (I can't seem to cut and paste the error text, frustratingly).\n\nSometimes when I see this error, I can restart the Browser Toolbox, and it attaches properly. This time, however, no matter how many times I restart the Browser Toolbox, it shows me the same error message."}, {"bug_id": 1615412, "tags": [], "count": 1, "is_private": false, "author": "mconley@mozilla.com", "time": "2020-02-13T19:24:59Z", "raw_text": "I'll also note that restarting the Firefox instance doesn't appear to help. The only thing I've ever found that helps is restarting the entire OS, which seems suboptimal.", "text": "I'll also note that restarting the Firefox instance doesn't appear to help. The only thing I've ever found that helps is restarting the entire OS, which seems suboptimal.", "id": 14640008, "attachment_id": null, "creator": "mconley@mozilla.com", "creation_time": "2020-02-13T19:24:59Z"}, {"is_private": false, "count": 2, "bug_id": 1615412, "tags": [], "id": 14640247, "text": "Created attachment 9126556\nbrowser_toolbox_split.png", "author": "mreschenberg@mozilla.com", "attachment_id": 9126556, "creator": "mreschenberg@mozilla.com", "time": "2020-02-13T21:08:19Z", "creation_time": "2020-02-13T21:08:19Z", "raw_text": ""}, {"creation_time": "2020-02-13T21:10:04Z", "creator": "bugzilla@digitarald.com", "attachment_id": null, "id": 14640253, "text": "Same problem, probably for 2 - 3 months now. Only OS restart fixes it. No Firefox's processes are otherwise running.\n\nRe Morgan's screenshot: If toolbox fails to connect, in most cases it will have a full page error dump. Only very rarely I get Morgan's split error toolbox state and recently it only shows up for a moment and then recovers.", "raw_text": "Same problem, probably for 2 - 3 months now. Only OS restart fixes it. No Firefox's processes are otherwise running.\n\nRe Morgan's screenshot: If toolbox fails to connect, in most cases it will have a full page error dump. Only very rarely I get Morgan's split error toolbox state and recently it only shows up for a moment and then recovers.", "time": "2020-02-13T21:10:04Z", "author": "bugzilla@digitarald.com", "bug_id": 1615412, "tags": [], "count": 3, "is_private": false}, {"text": "I'm running into a (related?) similar issue, which I'll document on this bug too, though it might be unrelated. Note restarting firefox and restarting my OS had no effect. \n\nSTR: \n\n1. Launch https://www.mozilla.org/media/contentcards/img/home-2019/card_2/guide-high-res.a12bff1c92ab.jpg\n2. Open browser toolbox with CMD + Option + Shift + I\n\nExpected:\n\nBrowser toolbox launches, attached to the current active window\n\nActual:\n\nSee screenshot browser_toolbox_split.png [Window titled \"Multiprocess Browser Toolbox\". The left half of the window is white, with JSON text titled \"Browser Toolbox connection status\". The JSON below the heading indicates the connection is successful. The right half of the window shows the normal browser toolbox. The left \"pane\" is not collapsible and does not vanish with use of the toolbox.]\n\nMy current nightly is from here: https://hg.mozilla.org/mozilla-central/rev/2f6870dd1b99edaba1de4d2aa97f3910a640c5bf\nI'm running OSX 10.15.3\nI also initially thought this might be a fission thing, but I disabled fission.autostart and got the same results.", "id": 14640257, "creation_time": "2020-02-13T21:12:17Z", "attachment_id": null, "creator": "mreschenberg@mozilla.com", "author": "mreschenberg@mozilla.com", "count": 4, "is_private": false, "tags": [], "bug_id": 1615412, "raw_text": "I'm running into a (related?) similar issue, which I'll document on this bug too, though it might be unrelated. Note restarting firefox and restarting my OS had no effect. \n\nSTR: \n\n1. Launch https://www.mozilla.org/media/contentcards/img/home-2019/card_2/guide-high-res.a12bff1c92ab.jpg\n2. Open browser toolbox with CMD + Option + Shift + I\n\nExpected:\n\nBrowser toolbox launches, attached to the current active window\n\nActual:\n\nSee screenshot browser_toolbox_split.png [Window titled \"Multiprocess Browser Toolbox\". The left half of the window is white, with JSON text titled \"Browser Toolbox connection status\". The JSON below the heading indicates the connection is successful. The right half of the window shows the normal browser toolbox. The left \"pane\" is not collapsible and does not vanish with use of the toolbox.]\n\nMy current nightly is from here: https://hg.mozilla.org/mozilla-central/rev/2f6870dd1b99edaba1de4d2aa97f3910a640c5bf\nI'm running OSX 10.15.3\nI also initially thought this might be a fission thing, but I disabled fission.autostart and got the same results.", "time": "2020-02-13T21:12:17Z"}, {"raw_text": "Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?", "creation_time": "2020-02-13T21:13:16Z", "time": "2020-02-13T21:13:16Z", "creator": "bugzilla@digitarald.com", "attachment_id": null, "author": "bugzilla@digitarald.com", "text": "Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?", "id": 14640258, "tags": [], "bug_id": 1615412, "count": 5, "is_private": false}, {"creation_time": "2020-02-13T21:13:43Z", "creator": "bugzilla@digitarald.com", "attachment_id": null, "id": 14640259, "text": "(See comment above)", "raw_text": "(See comment above)", "time": "2020-02-13T21:13:43Z", "author": "bugzilla@digitarald.com", "bug_id": 1615412, "tags": [], "is_private": false, "count": 6}, {"author": "poirot.alex@gmail.com", "is_private": false, "count": 7, "tags": [], "bug_id": 1615412, "raw_text": "(In reply to :Harald Kirschner :digitarald from comment #5)\n> Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?\n\nI couldn't think about anything in particular, but Nicolas just hit an exception and was able to capture it.\nAnd it is related to fission work.\n```\nconsole.error: \"Error while calling actor 'root's method 'listRemoteFrames'\" \"currentContext.getChildren is not a function\"\nconsole.error: \"listRemoteFrames@resource://devtools/server/actors/root.js:650:45\\nasync*handler@resource://devtools/shared/protocol/Actor.js:154:37\\nonPacket@resource://devtools/server/devtools-server-connection.js:380:58\\n_onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:464:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\n\"\nconsole.error: \"Exception while opening the toolbox\" \"Error: Protocol error (unknownError): currentContext.getChildren is not a function\" (new Error(\"Protocol error (unknownError): currentContext.getChildren is not a function\", \"resource://devtools/shared/protocol/Front.js\", 294))\nonPacket/<@resource://devtools/shared/protocol/Front.js:294:31\nDevTools RDP*request@resource://devtools/shared/protocol/Front.js:232:14\ngenerateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:49:19\nlistRemoteFrames@resource://devtools/shared/fronts/targets/browsing-context.js:132:33\nlisten@resource://devtools/shared/resources/target-list.js:90:42\nstartListening@resource://devtools/shared/resources/target-list.js:324:47\nasync*open/<@resource://devtools/client/framework/toolbox.js:754:29\nopen@resource://devtools/client/framework/toolbox.js:899:18\ncreateToolbox@resource://devtools/client/framework/devtools.js:622:19\nasync*showToolbox@resource://devtools/client/framework/devtools.js:509:35\nopenToolbox@chrome://devtools/content/framework/browser-toolbox/window.js:205:30\nconnect@chrome://devtools/content/framework/browser-toolbox/window.js:112:9\nasync*@chrome://devtools/content/framework/browser-toolbox/window.js:162:13\nEventListener.handleEvent*@chrome://devtools/content/framework/browser-toolbox/window.js:140:8\n```\n\nIt looks like in this new code:\nhttps://searchfox.org/mozilla-central/rev/49ed791eec93335abfe6c2880f84c324e73e47e6/devtools/server/actors/root.js#649\n`currentContext` is sometimes undefined.", "time": "2020-02-26T16:58:11Z", "text": "(In reply to :Harald Kirschner :digitarald from comment #5)\n> Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?\n\nI couldn't think about anything in particular, but Nicolas just hit an exception and was able to capture it.\nAnd it is related to fission work.\n```\nconsole.error: \"Error while calling actor 'root's method 'listRemoteFrames'\" \"currentContext.getChildren is not a function\"\nconsole.error: \"listRemoteFrames@resource://devtools/server/actors/root.js:650:45\\nasync*handler@resource://devtools/shared/protocol/Actor.js:154:37\\nonPacket@resource://devtools/server/devtools-server-connection.js:380:58\\n_onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:464:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\n\"\nconsole.error: \"Exception while opening the toolbox\" \"Error: Protocol error (unknownError): currentContext.getChildren is not a function\" (new Error(\"Protocol error (unknownError): currentContext.getChildren is not a function\", \"resource://devtools/shared/protocol/Front.js\", 294))\nonPacket/<@resource://devtools/shared/protocol/Front.js:294:31\nDevTools RDP*request@resource://devtools/shared/protocol/Front.js:232:14\ngenerateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:49:19\nlistRemoteFrames@resource://devtools/shared/fronts/targets/browsing-context.js:132:33\nlisten@resource://devtools/shared/resources/target-list.js:90:42\nstartListening@resource://devtools/shared/resources/target-list.js:324:47\nasync*open/<@resource://devtools/client/framework/toolbox.js:754:29\nopen@resource://devtools/client/framework/toolbox.js:899:18\ncreateToolbox@resource://devtools/client/framework/devtools.js:622:19\nasync*showToolbox@resource://devtools/client/framework/devtools.js:509:35\nopenToolbox@chrome://devtools/content/framework/browser-toolbox/window.js:205:30\nconnect@chrome://devtools/content/framework/browser-toolbox/window.js:112:9\nasync*@chrome://devtools/content/framework/browser-toolbox/window.js:162:13\nEventListener.handleEvent*@chrome://devtools/content/framework/browser-toolbox/window.js:140:8\n```\n\nIt looks like in this new code:\nhttps://searchfox.org/mozilla-central/rev/49ed791eec93335abfe6c2880f84c324e73e47e6/devtools/server/actors/root.js#649\n`currentContext` is sometimes undefined.", "id": 14663214, "creation_time": "2020-02-26T16:58:11Z", "attachment_id": null, "creator": "poirot.alex@gmail.com"}, {"text": "I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly.", "id": 14699007, "attachment_id": null, "creator": "mconley@mozilla.com", "creation_time": "2020-03-16T19:29:15Z", "count": 8, "is_private": false, "bug_id": 1615412, "tags": [], "author": "mconley@mozilla.com", "time": "2020-03-16T19:29:15Z", "raw_text": "I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly."}, {"text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #8)\n> I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly.\n\n+1 I haven't been able to use either (since reporting here) :(", "id": 14699009, "creator": "mreschenberg@mozilla.com", "attachment_id": null, "creation_time": "2020-03-16T19:29:59Z", "is_private": false, "count": 9, "tags": [], "bug_id": 1615412, "author": "mreschenberg@mozilla.com", "time": "2020-03-16T19:29:59Z", "raw_text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #8)\n> I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly.\n\n+1 I haven't been able to use either (since reporting here) :("}, {"creation_time": "2020-03-16T20:54:43Z", "attachment_id": null, "creator": "bgrinstead@mozilla.com", "text": "(In reply to Alexandre Poirot [:ochameau] from comment #7)\n> (In reply to :Harald Kirschner :digitarald from comment #5)\n> > Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?\n> \n> I couldn't think about anything in particular, but Nicolas just hit an exception and was able to capture it.\n> And it is related to fission work.\n> ```\n> console.error: \"Error while calling actor 'root's method 'listRemoteFrames'\" \"currentContext.getChildren is not a function\"\n> console.error: \"listRemoteFrames@resource://devtools/server/actors/root.js:650:45\\nasync*handler@resource://devtools/shared/protocol/Actor.js:154:37\\nonPacket@resource://devtools/server/devtools-server-connection.js:380:58\\n_onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:464:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\n\"\n> console.error: \"Exception while opening the toolbox\" \"Error: Protocol error (unknownError): currentContext.getChildren is not a function\" (new Error(\"Protocol error (unknownError): currentContext.getChildren is not a function\", \"resource://devtools/shared/protocol/Front.js\", 294))\n> onPacket/<@resource://devtools/shared/protocol/Front.js:294:31\n> DevTools RDP*request@resource://devtools/shared/protocol/Front.js:232:14\n> generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:49:19\n> listRemoteFrames@resource://devtools/shared/fronts/targets/browsing-context.js:132:33\n> listen@resource://devtools/shared/resources/target-list.js:90:42\n> startListening@resource://devtools/shared/resources/target-list.js:324:47\n> async*open/<@resource://devtools/client/framework/toolbox.js:754:29\n> open@resource://devtools/client/framework/toolbox.js:899:18\n> createToolbox@resource://devtools/client/framework/devtools.js:622:19\n> async*showToolbox@resource://devtools/client/framework/devtools.js:509:35\n> openToolbox@chrome://devtools/content/framework/browser-toolbox/window.js:205:30\n> connect@chrome://devtools/content/framework/browser-toolbox/window.js:112:9\n> async*@chrome://devtools/content/framework/browser-toolbox/window.js:162:13\n> EventListener.handleEvent*@chrome://devtools/content/framework/browser-toolbox/window.js:140:8\n> ```\n> \n> It looks like in this new code:\n> https://searchfox.org/mozilla-central/rev/49ed791eec93335abfe6c2880f84c324e73e47e6/devtools/server/actors/root.js#649\n> `currentContext` is sometimes undefined.\n\nMaybe we could more gracefully fail in that case in the meantime? Maybe filtering out null browsingContexts before pushing them onto contextsToWalk in https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 would work? Given Comments 8 and 9 that would be helpful.\n\nAlso Mike, do you have any idea _why_ we might be getting a null browsingContext on that line above? Like, in what case a browser element in in the DOM browser.xhtml wouldn't have a browsingContext.", "id": 14699175, "raw_text": "(In reply to Alexandre Poirot [:ochameau] from comment #7)\n> (In reply to :Harald Kirschner :digitarald from comment #5)\n> > Alex, any idea if Multiprocess Toolbox work could have regressed this or any other leads?\n> \n> I couldn't think about anything in particular, but Nicolas just hit an exception and was able to capture it.\n> And it is related to fission work.\n> ```\n> console.error: \"Error while calling actor 'root's method 'listRemoteFrames'\" \"currentContext.getChildren is not a function\"\n> console.error: \"listRemoteFrames@resource://devtools/server/actors/root.js:650:45\\nasync*handler@resource://devtools/shared/protocol/Actor.js:154:37\\nonPacket@resource://devtools/server/devtools-server-connection.js:380:58\\n_onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:464:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\\n\"\n> console.error: \"Exception while opening the toolbox\" \"Error: Protocol error (unknownError): currentContext.getChildren is not a function\" (new Error(\"Protocol error (unknownError): currentContext.getChildren is not a function\", \"resource://devtools/shared/protocol/Front.js\", 294))\n> onPacket/<@resource://devtools/shared/protocol/Front.js:294:31\n> DevTools RDP*request@resource://devtools/shared/protocol/Front.js:232:14\n> generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:49:19\n> listRemoteFrames@resource://devtools/shared/fronts/targets/browsing-context.js:132:33\n> listen@resource://devtools/shared/resources/target-list.js:90:42\n> startListening@resource://devtools/shared/resources/target-list.js:324:47\n> async*open/<@resource://devtools/client/framework/toolbox.js:754:29\n> open@resource://devtools/client/framework/toolbox.js:899:18\n> createToolbox@resource://devtools/client/framework/devtools.js:622:19\n> async*showToolbox@resource://devtools/client/framework/devtools.js:509:35\n> openToolbox@chrome://devtools/content/framework/browser-toolbox/window.js:205:30\n> connect@chrome://devtools/content/framework/browser-toolbox/window.js:112:9\n> async*@chrome://devtools/content/framework/browser-toolbox/window.js:162:13\n> EventListener.handleEvent*@chrome://devtools/content/framework/browser-toolbox/window.js:140:8\n> ```\n> \n> It looks like in this new code:\n> https://searchfox.org/mozilla-central/rev/49ed791eec93335abfe6c2880f84c324e73e47e6/devtools/server/actors/root.js#649\n> `currentContext` is sometimes undefined.\n\nMaybe we could more gracefully fail in that case in the meantime? Maybe filtering out null browsingContexts before pushing them onto contextsToWalk in https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 would work? Given Comments 8 and 9 that would be helpful.\n\nAlso Mike, do you have any idea _why_ we might be getting a null browsingContext on that line above? Like, in what case a browser element in in the DOM browser.xhtml wouldn't have a browsingContext.", "time": "2020-03-16T20:54:43Z", "author": "bgrinstead@mozilla.com", "bug_id": 1615412, "tags": [], "is_private": false, "count": 10}, {"attachment_id": null, "creator": "bgrinstead@mozilla.com", "creation_time": "2020-03-16T20:57:25Z", "id": 14699180, "text": "Mike or Morgan, if you don't mind testing locally and you could add `.filter(browsingContext => browsingContext)` right after `.map(browser => browser.browsingContext)` at https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 to see if that helps based on Comment 10.", "time": "2020-03-16T20:57:25Z", "raw_text": "Mike or Morgan, if you don't mind testing locally and you could add `.filter(browsingContext => browsingContext)` right after `.map(browser => browser.browsingContext)` at https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 to see if that helps based on Comment 10.", "count": 11, "is_private": false, "tags": [], "bug_id": 1615412, "author": "bgrinstead@mozilla.com"}, {"creation_time": "2020-03-16T21:16:28Z", "creator": "mconley@mozilla.com", "attachment_id": null, "text": "(In reply to Brian Grinstead [:bgrins] from comment #11)\n> Mike or Morgan, if you don't mind testing locally and you could add `.filter(browsingContext => browsingContext)` right after `.map(browser => browser.browsingContext)` at https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 to see if that helps based on Comment 10.\n\nI'm afraid that didn't change the behaviour.\n\n(In reply to Brian Grinstead [:bgrins] from comment #10)\n> Also Mike, do you have any idea _why_ we might be getting a null browsingContext on that line above? Like, in what case a browser element in in the DOM browser.xhtml wouldn't have a browsingContext.\n\nThe only situation I can think of where a <browser> might not have a BrowsingContext is if it's not yet been assigned a FrameLoader / been attached to the DOM. Nika, are there other cases I haven't thought of?", "id": 14699217, "raw_text": "(In reply to Brian Grinstead [:bgrins] from comment #11)\n> Mike or Morgan, if you don't mind testing locally and you could add `.filter(browsingContext => browsingContext)` right after `.map(browser => browser.browsingContext)` at https://searchfox.org/mozilla-central/rev/d69ec052bed8700af7a283e37b60b4af22734930/devtools/server/actors/root.js#604 to see if that helps based on Comment 10.\n\nI'm afraid that didn't change the behaviour.\n\n(In reply to Brian Grinstead [:bgrins] from comment #10)\n> Also Mike, do you have any idea _why_ we might be getting a null browsingContext on that line above? Like, in what case a browser element in in the DOM browser.xhtml wouldn't have a browsingContext.\n\nThe only situation I can think of where a <browser> might not have a BrowsingContext is if it's not yet been assigned a FrameLoader / been attached to the DOM. Nika, are there other cases I haven't thought of?", "time": "2020-03-16T21:16:28Z", "author": "mconley@mozilla.com", "tags": [], "bug_id": 1615412, "count": 12, "is_private": false}, {"author": "poirot.alex@gmail.com", "count": 13, "is_private": false, "bug_id": 1615412, "tags": [], "raw_text": "Sorry, this fell through the cracks... \nI'm activity working on bug 1593937 which will get rid of this code.\nSimilar issue might happen in the new code, so it would be handy to better understand what is wrong here.\n\nNow that I read the exception more carefully `\"currentContext.getChildren is not a function\"`\n`currentContext` isn't undefined, but it is rather the `getChildren` attribute which is not defined.\nI'm wondering if Nicolas only hit a rebase issue, when testing Firefox in between two builds when `getChildren` has been renamed to `children`.\nIf that is that, the issue may not be related to this code after all.\n\nMike, Morgan, are you seeing any error in your terminal? Or in the Browser Console?", "time": "2020-03-16T21:26:16Z", "id": 14699228, "text": "Sorry, this fell through the cracks... \nI'm activity working on bug 1593937 which will get rid of this code.\nSimilar issue might happen in the new code, so it would be handy to better understand what is wrong here.\n\nNow that I read the exception more carefully `\"currentContext.getChildren is not a function\"`\n`currentContext` isn't undefined, but it is rather the `getChildren` attribute which is not defined.\nI'm wondering if Nicolas only hit a rebase issue, when testing Firefox in between two builds when `getChildren` has been renamed to `children`.\nIf that is that, the issue may not be related to this code after all.\n\nMike, Morgan, are you seeing any error in your terminal? Or in the Browser Console?", "creation_time": "2020-03-16T21:26:16Z", "attachment_id": null, "creator": "poirot.alex@gmail.com"}, {"time": "2020-03-16T21:29:11Z", "raw_text": "Please correct me if I'm wrong, but I think the issue isn't about an issue around BrowsingContext.\nAt least we can't say that from comment 7 exception, which might just be a rebase issue.\n\nSo, I'm reseting the unecessary neeinfo on nika.", "is_private": false, "count": 14, "bug_id": 1615412, "tags": [], "author": "poirot.alex@gmail.com", "attachment_id": null, "creator": "poirot.alex@gmail.com", "creation_time": "2020-03-16T21:29:11Z", "text": "Please correct me if I'm wrong, but I think the issue isn't about an issue around BrowsingContext.\nAt least we can't say that from comment 7 exception, which might just be a rebase issue.\n\nSo, I'm reseting the unecessary neeinfo on nika.", "id": 14699232}, {"tags": [], "bug_id": 1615412, "count": 15, "is_private": false, "author": "poirot.alex@gmail.com", "time": "2020-03-16T21:33:38Z", "raw_text": "I tried really hard reproducing but can't find any way to make it fail.\nI'm wondering if this is specific to OSX and might be about processes. i.e. how we execute the browser toolbox process.\nAre you all on OSX? Any particular preference, page or window opened?", "id": 14699238, "text": "I tried really hard reproducing but can't find any way to make it fail.\nI'm wondering if this is specific to OSX and might be about processes. i.e. how we execute the browser toolbox process.\nAre you all on OSX? Any particular preference, page or window opened?", "attachment_id": null, "creator": "poirot.alex@gmail.com", "creation_time": "2020-03-16T21:33:38Z"}, {"is_private": false, "count": 16, "bug_id": 1615412, "tags": [], "author": "nchevobbe@mozilla.com", "time": "2020-03-17T07:21:47Z", "raw_text": "I do see it from time to time too, I often only have https://nchevobbe.github.io/demo/console-test-app.html open on my main Firefox window.\nBug 1591590 is a test intermittent about the browser toolbox, and the screenshots indicate we get into that weird state there too.", "text": "I do see it from time to time too, I often only have https://nchevobbe.github.io/demo/console-test-app.html open on my main Firefox window.\nBug 1591590 is a test intermittent about the browser toolbox, and the screenshots indicate we get into that weird state there too.", "id": 14699825, "creator": "nchevobbe@mozilla.com", "attachment_id": null, "creation_time": "2020-03-17T07:21:47Z"}, {"raw_text": "Yes, I'm on macOS. I can reproduce this even with a new profile, and no other Firefox instance running.", "time": "2020-03-17T16:48:21Z", "author": "mconley@mozilla.com", "tags": [], "bug_id": 1615412, "count": 17, "is_private": false, "creation_time": "2020-03-17T16:48:21Z", "creator": "mconley@mozilla.com", "attachment_id": null, "id": 14700710, "text": "Yes, I'm on macOS. I can reproduce this even with a new profile, and no other Firefox instance running."}, {"creation_time": "2020-04-01T09:40:06Z", "raw_text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #8)\n> I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly.\n\nSame here.", "attachment_id": null, "creator": "dao+bmo@mozilla.com", "time": "2020-04-01T09:40:06Z", "author": "dao+bmo@mozilla.com", "id": 14728570, "text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #8)\n> I'll note that I haven't been able to properly use the Browser Toolbox for several weeks now. Even after restarts, I seem to enter this state pretty regularly.\n\nSame here.", "count": 18, "is_private": false, "bug_id": 1615412, "tags": []}, {"creation_time": "2020-04-01T13:54:15Z", "creator": "mconley@mozilla.com", "attachment_id": null, "text": "(In reply to D\u00e3o Gottwald [::dao] from comment #18)\n> Same here.\n\nIs this on your Linux machine?", "id": 14729006, "raw_text": "(In reply to D\u00e3o Gottwald [::dao] from comment #18)\n> Same here.\n\nIs this on your Linux machine?", "time": "2020-04-01T13:54:15Z", "author": "mconley@mozilla.com", "count": 19, "is_private": false, "tags": [], "bug_id": 1615412}, {"text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #19)\n> (In reply to D\u00e3o Gottwald [::dao] from comment #18)\n> > Same here.\n> \n> Is this on your Linux machine?\n\nYeah, Ubuntu 19.10.", "id": 14729074, "attachment_id": null, "creator": "dao+bmo@mozilla.com", "creation_time": "2020-04-01T14:17:22Z", "bug_id": 1615412, "tags": [], "count": 20, "is_private": false, "author": "dao+bmo@mozilla.com", "time": "2020-04-01T14:17:22Z", "raw_text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #19)\n> (In reply to D\u00e3o Gottwald [::dao] from comment #18)\n> > Same here.\n> \n> Is this on your Linux machine?\n\nYeah, Ubuntu 19.10."}, {"attachment_id": null, "creator": "mconley@mozilla.com", "creation_time": "2020-04-06T18:53:29Z", "id": 14738875, "text": "Okay, I decided to roll up my sleeves and look at this, because I really miss using this tool.\n\nI _think_ I've made some headway. Here's what I know:\n\n1. The server seems to launch correctly.\n2. The problem appears to be in the toolbox profile that launches - the connection attempt fails, despite the server running\n3. If I Telnet to the server port locally, I get the following:\n\n```\nmconleys-MBP:~ mikeconley$ telnet\ntelnet> open localhost 54166\nTrying ::1...\ntelnet: connect to address ::1: Connection refused\nTrying 127.0.0.1...\nConnected to localhost.\nEscape character is '^]'.\n304:{\"from\":\"root\",\"applicationType\":\"browser\",\"testConnectionPrefix\":\"server1.conn1.\",\"traits\":{\"sources\":true,\"networkMonitor\":true,\"storageInspector\":true,\"wasmBinarySource\":true,\"bulk\":true,\"webConsoleCommands\":true,\"allowChromeProcess\":true,\"heapSnapshots\":true,\"perfActorVersion\":1,\"watchpoints\":true}}Connection closed by foreign host.\n```\n\nInterestingly, the first attempt that Telnet makes is refused - presumably, because it's trying to connect via an ipv6 address? And then it falls back to ipv4... I think.\n\nSo I was able to get things working locally by monkeypatching this line here:\n\nhttps://searchfox.org/mozilla-central/rev/4d2a9d5dc8f0e65807ee66e2b04c64596c643b7a/devtools/client/framework/browser-toolbox/window.js#103\n\nfrom:\n\n```\n  const host = Prefs.chromeDebuggingHost;\n```\n\nto\n\n```\n  const host = \"127.0.0.1\";\n```\n\nand now it works?\n\nI'm not sure why this would kind of thing would only rear itself after some time after the OS has been running. Maybe someone from the Necko team could comment, because this looks more like a local networking issue that our DevTools is stumbling on.", "time": "2020-04-06T18:53:29Z", "raw_text": "Okay, I decided to roll up my sleeves and look at this, because I really miss using this tool.\n\nI _think_ I've made some headway. Here's what I know:\n\n1. The server seems to launch correctly.\n2. The problem appears to be in the toolbox profile that launches - the connection attempt fails, despite the server running\n3. If I Telnet to the server port locally, I get the following:\n\n```\nmconleys-MBP:~ mikeconley$ telnet\ntelnet> open localhost 54166\nTrying ::1...\ntelnet: connect to address ::1: Connection refused\nTrying 127.0.0.1...\nConnected to localhost.\nEscape character is '^]'.\n304:{\"from\":\"root\",\"applicationType\":\"browser\",\"testConnectionPrefix\":\"server1.conn1.\",\"traits\":{\"sources\":true,\"networkMonitor\":true,\"storageInspector\":true,\"wasmBinarySource\":true,\"bulk\":true,\"webConsoleCommands\":true,\"allowChromeProcess\":true,\"heapSnapshots\":true,\"perfActorVersion\":1,\"watchpoints\":true}}Connection closed by foreign host.\n```\n\nInterestingly, the first attempt that Telnet makes is refused - presumably, because it's trying to connect via an ipv6 address? And then it falls back to ipv4... I think.\n\nSo I was able to get things working locally by monkeypatching this line here:\n\nhttps://searchfox.org/mozilla-central/rev/4d2a9d5dc8f0e65807ee66e2b04c64596c643b7a/devtools/client/framework/browser-toolbox/window.js#103\n\nfrom:\n\n```\n  const host = Prefs.chromeDebuggingHost;\n```\n\nto\n\n```\n  const host = \"127.0.0.1\";\n```\n\nand now it works?\n\nI'm not sure why this would kind of thing would only rear itself after some time after the OS has been running. Maybe someone from the Necko team could comment, because this looks more like a local networking issue that our DevTools is stumbling on.", "bug_id": 1615412, "tags": [], "count": 21, "is_private": false, "author": "mconley@mozilla.com"}, {"author": "mconley@mozilla.com", "tags": [], "bug_id": 1615412, "is_private": false, "count": 22, "raw_text": "FWIW, I have the following in my `/etc/hosts` file:\n\n```\n127.0.0.1       localhost\n127.0.0.1       localhost2\n127.0.0.1       localhost3\n255.255.255.255 broadcasthost\n::1             localhost\nfe80::1%lo0     localhost\n```", "time": "2020-04-06T19:39:48Z", "id": 14738986, "text": "FWIW, I have the following in my `/etc/hosts` file:\n\n```\n127.0.0.1       localhost\n127.0.0.1       localhost2\n127.0.0.1       localhost3\n255.255.255.255 broadcasthost\n::1             localhost\nfe80::1%lo0     localhost\n```", "creation_time": "2020-04-06T19:39:48Z", "attachment_id": null, "creator": "mconley@mozilla.com"}, {"count": 23, "is_private": false, "bug_id": 1615412, "tags": [], "author": "valentin.gosu@gmail.com", "time": "2020-04-07T15:36:58Z", "raw_text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #22)\n> FWIW, I have the following in my `/etc/hosts` file:\n> \n> ```\n> 127.0.0.1       localhost\n> 127.0.0.1       localhost2\n> 127.0.0.1       localhost3\n> 255.255.255.255 broadcasthost\n> ::1             localhost\n> fe80::1%lo0     localhost\n> ```\n\nI normally expect only ipv4 addresses for localhost, an ipv6 for ip6-localhost.\nBut in any case, I don't know where we create the server socket, but I suspect we only bind it to the IPv4 address?\nNormally if we get an IPv6 address for localhost we should fallback to IPv4 if there's an error, but maybe that doesn't work?\nThere's a lot of stuff in the devtools socket implementation, so I'm not sure how that all works, but I assume we could add a\n```\nif (useIPv4Only) {\n  s.connectionFlags |= nsISocketTransport.DISABLE_IPV6;\n}\n```\n around [here](https://searchfox.org/mozilla-central/rev/4d2a9d5dc8f0e65807ee66e2b04c64596c643b7a/devtools/shared/security/socket.js#281) somewhere.", "id": 14740630, "text": "(In reply to Mike Conley (:mconley) (:\u2699\ufe0f) from comment #22)\n> FWIW, I have the following in my `/etc/hosts` file:\n> \n> ```\n> 127.0.0.1       localhost\n> 127.0.0.1       localhost2\n> 127.0.0.1       localhost3\n> 255.255.255.255 broadcasthost\n> ::1             localhost\n> fe80::1%lo0     localhost\n> ```\n\nI normally expect only ipv4 addresses for localhost, an ipv6 for ip6-localhost.\nBut in any case, I don't know where we create the server socket, but I suspect we only bind it to the IPv4 address?\nNormally if we get an IPv6 address for localhost we should fallback to IPv4 if there's an error, but maybe that doesn't work?\nThere's a lot of stuff in the devtools socket implementation, so I'm not sure how that all works, but I assume we could add a\n```\nif (useIPv4Only) {\n  s.connectionFlags |= nsISocketTransport.DISABLE_IPV6;\n}\n```\n around [here](https://searchfox.org/mozilla-central/rev/4d2a9d5dc8f0e65807ee66e2b04c64596c643b7a/devtools/shared/security/socket.js#281) somewhere.", "attachment_id": null, "creator": "valentin.gosu@gmail.com", "creation_time": "2020-04-07T15:36:58Z"}, {"creation_time": "2020-04-07T16:08:30Z", "creator": "bugzilla@digitarald.com", "attachment_id": null, "text": "P1, as many Firefox engineers are frequently affected.", "id": 14740686, "raw_text": "P1, as many Firefox engineers are frequently affected.", "time": "2020-04-07T16:08:30Z", "author": "bugzilla@digitarald.com", "is_private": false, "count": 24, "bug_id": 1615412, "tags": []}, {"creation_time": "2020-04-07T16:52:30Z", "raw_text": "I'll note that commenting this line out from my `/etc/hosts/` file seems to do the job:\n\n```\n::1             localhost\n```\n\nnow the Browser Toolbox works without me needing to patch it. \\o/\n\nI have no idea when or why I added that `/etc/hosts` line, tbh.", "creator": "mconley@mozilla.com", "attachment_id": null, "time": "2020-04-07T16:52:30Z", "author": "mconley@mozilla.com", "text": "I'll note that commenting this line out from my `/etc/hosts/` file seems to do the job:\n\n```\n::1             localhost\n```\n\nnow the Browser Toolbox works without me needing to patch it. \\o/\n\nI have no idea when or why I added that `/etc/hosts` line, tbh.", "id": 14740796, "count": 25, "is_private": false, "tags": [], "bug_id": 1615412}, {"text": "Just for reference, this is my hosts file for macOS, but I didn't have the connection issue in the past 4+ weeks.\n\n```\n127.0.0.1      \tlocalhost\n255.255.255.255\tbroadcasthost\n::1             localhost\nfe80::1%lo0\tlocalhost\n```", "id": 14741115, "attachment_id": null, "creator": "bugzilla@digitarald.com", "creation_time": "2020-04-07T17:45:15Z", "is_private": false, "count": 26, "tags": [], "bug_id": 1615412, "author": "bugzilla@digitarald.com", "time": "2020-04-07T17:45:15Z", "raw_text": "Just for reference, this is my hosts file for macOS, but I didn't have the connection issue in the past 4+ weeks.\n\n```\n127.0.0.1      \tlocalhost\n255.255.255.255\tbroadcasthost\n::1             localhost\nfe80::1%lo0\tlocalhost\n```"}, {"time": "2020-04-07T18:01:30Z", "creator": "valentin.gosu@gmail.com", "attachment_id": null, "creation_time": "2020-04-07T18:01:30Z", "raw_text": "(In reply to :Harald Kirschner :digitarald from comment #26)\n> Just for reference, this is my hosts file for macOS, but I didn't have the connection issue in the past 4+ weeks.\n> \n> ```\n> 127.0.0.1      \tlocalhost\n> 255.255.255.255\tbroadcasthost\n> ::1             localhost\n> fe80::1%lo0\tlocalhost\n> ```\n\nSeems like this is a mac thing? Either way, I think adding the DISABLE_IPV6 flag should fix this.", "bug_id": 1615412, "tags": [], "count": 27, "is_private": false, "author": "valentin.gosu@gmail.com", "id": 14741163, "text": "(In reply to :Harald Kirschner :digitarald from comment #26)\n> Just for reference, this is my hosts file for macOS, but I didn't have the connection issue in the past 4+ weeks.\n> \n> ```\n> 127.0.0.1      \tlocalhost\n> 255.255.255.255\tbroadcasthost\n> ::1             localhost\n> fe80::1%lo0\tlocalhost\n> ```\n\nSeems like this is a mac thing? Either way, I think adding the DISABLE_IPV6 flag should fix this."}, {"bug_id": 1615412, "tags": [], "count": 28, "is_private": false, "author": "poirot.alex@gmail.com", "time": "2020-04-15T14:55:14Z", "raw_text": "", "text": "Created attachment 9140778\nBug 1615412 - Disable IPv6 when connecting to remote runtime.", "id": 14756951, "creator": "poirot.alex@gmail.com", "attachment_id": 9140778, "creation_time": "2020-04-15T14:55:14Z"}, {"id": 14756981, "text": "It would be super nice if someone able to reproduce this issue could apply this patch and confirm that it actually address it!", "creation_time": "2020-04-15T15:06:59Z", "attachment_id": null, "creator": "poirot.alex@gmail.com", "author": "poirot.alex@gmail.com", "bug_id": 1615412, "tags": [], "is_private": false, "count": 29, "raw_text": "It would be super nice if someone able to reproduce this issue could apply this patch and confirm that it actually address it!", "time": "2020-04-15T15:06:59Z"}, {"raw_text": "Hi Mike, could you apply this patch whenever you reproduce the issue so that we can confirm this patch is actually effectice?", "time": "2020-04-16T15:43:09Z", "author": "poirot.alex@gmail.com", "tags": [], "bug_id": 1615412, "count": 30, "is_private": false, "creation_time": "2020-04-16T15:43:09Z", "creator": "poirot.alex@gmail.com", "attachment_id": null, "id": 14759324, "text": "Hi Mike, could you apply this patch whenever you reproduce the issue so that we can confirm this patch is actually effectice?"}, {"id": 14759375, "text": "I reverted my /etc/hosts fix, and was able to reproduce the issue. I then applied the patch, and the issue appears to be solved with it! Thanks!", "attachment_id": null, "creator": "mconley@mozilla.com", "creation_time": "2020-04-16T16:00:06Z", "bug_id": 1615412, "tags": [], "is_private": false, "count": 31, "author": "mconley@mozilla.com", "time": "2020-04-16T16:00:06Z", "raw_text": "I reverted my /etc/hosts fix, and was able to reproduce the issue. I then applied the patch, and the issue appears to be solved with it! Thanks!"}, {"id": 14759489, "text": "Pushed by apoirot@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/d920b65e3cfa\nDisable IPv6 when connecting to remote runtime. r=jdescottes", "attachment_id": null, "creator": "pulsebot@bots.tld", "creation_time": "2020-04-16T16:41:45Z", "count": 32, "is_private": false, "bug_id": 1615412, "tags": [], "author": "pulsebot@bots.tld", "time": "2020-04-16T16:41:45Z", "raw_text": "Pushed by apoirot@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/d920b65e3cfa\nDisable IPv6 when connecting to remote runtime. r=jdescottes"}, {"bug_id": 1615412, "tags": [], "count": 33, "is_private": false, "author": "poirot.alex@gmail.com", "time": "2020-04-16T16:42:30Z", "raw_text": "Thanks a lot for testing!\n\nD\u00e3o, Morgan, if you still see any issue after this bug lands, please let us know!", "id": 14759494, "text": "Thanks a lot for testing!\n\nD\u00e3o, Morgan, if you still see any issue after this bug lands, please let us know!", "creator": "poirot.alex@gmail.com", "attachment_id": null, "creation_time": "2020-04-16T16:42:30Z"}, {"creation_time": "2020-04-17T09:41:03Z", "creator": "dluca@mozilla.com", "attachment_id": null, "id": 14761038, "text": "https://hg.mozilla.org/mozilla-central/rev/d920b65e3cfa", "raw_text": "https://hg.mozilla.org/mozilla-central/rev/d920b65e3cfa", "time": "2020-04-17T09:41:03Z", "author": "dluca@mozilla.com", "bug_id": 1615412, "tags": ["bugherder"], "is_private": false, "count": 34}, {"id": 14761492, "text": "The patch didn't help over here on Linux. My `hosts` file has `::1` for `ip6-localhost` but not for `localhost`.", "author": "dao+bmo@mozilla.com", "bug_id": 1615412, "tags": [], "is_private": false, "count": 35, "raw_text": "The patch didn't help over here on Linux. My `hosts` file has `::1` for `ip6-localhost` but not for `localhost`.", "creation_time": "2020-04-17T13:58:47Z", "time": "2020-04-17T13:58:47Z", "attachment_id": null, "creator": "dao+bmo@mozilla.com"}, {"raw_text": "The patch landed in nightly and beta is affected.\n:ochameau, is this bug important enough to require an uplift?\nIf not please set `status_beta` to `wontfix`.\n\n\nFor more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#uplift_beta.py).", "time": "2020-04-20T12:00:49Z", "author": "release-mgmt-account-bot@mozilla.tld", "count": 36, "is_private": false, "bug_id": 1615412, "tags": [], "creation_time": "2020-04-20T12:00:49Z", "attachment_id": null, "creator": "release-mgmt-account-bot@mozilla.tld", "text": "The patch landed in nightly and beta is affected.\n:ochameau, is this bug important enough to require an uplift?\nIf not please set `status_beta` to `wontfix`.\n\n\nFor more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#uplift_beta.py).", "id": 14766223}, {"text": "I just ran into this again on OSX, with `77.0a1 (2020-04-21) (64-bit)`.\n\nCuriously I was able to open another toolbox on the failed toolbox to copy the error out:\n\n```\nException { name: \"NS_ERROR_CONNECTION_REFUSED\", message: \"Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIInputStream.available]\", result: 2152398861, filename: \"resource://devtools/shared/security/socket.js\", lineNumber: 363, columnNumber: 0, data: null, stack: \"onInputStreamReady@resource://devtools/shared/security/socket.js:363:18\\n\", location: XPCWrappedNative_NoHelper }\nwindow.js:173:15\n```", "id": 14770751, "creator": "bugzilla@digitarald.com", "attachment_id": null, "creation_time": "2020-04-22T03:47:24Z", "bug_id": 1615412, "tags": [], "count": 37, "is_private": false, "author": "bugzilla@digitarald.com", "time": "2020-04-22T03:47:24Z", "raw_text": "I just ran into this again on OSX, with `77.0a1 (2020-04-21) (64-bit)`.\n\nCuriously I was able to open another toolbox on the failed toolbox to copy the error out:\n\n```\nException { name: \"NS_ERROR_CONNECTION_REFUSED\", message: \"Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIInputStream.available]\", result: 2152398861, filename: \"resource://devtools/shared/security/socket.js\", lineNumber: 363, columnNumber: 0, data: null, stack: \"onInputStreamReady@resource://devtools/shared/security/socket.js:363:18\\n\", location: XPCWrappedNative_NoHelper }\nwindow.js:173:15\n```"}, {"creation_time": "2020-05-11T10:33:54Z", "attachment_id": null, "creator": "odvarko@gmail.com", "id": 14809083, "text": "Alex, there are reports indicating that the following bug isn't fully fixed (comment #35 and comment #37), so I am reopening it.\n\nHonza", "raw_text": "Alex, there are reports indicating that the following bug isn't fully fixed (comment #35 and comment #37), so I am reopening it.\n\nHonza", "time": "2020-05-11T10:33:54Z", "author": "odvarko@gmail.com", "is_private": false, "count": 38, "bug_id": 1615412, "tags": []}, {"attachment_id": null, "creator": "mozilla+bmo@noorenberghe.ca", "creation_time": "2020-05-18T17:40:37Z", "text": "I just hit this error on Nightly due to a version mismatch from a Nightly update but I believe that should be handled in a separate bug (maybe even to just give a better error message). Restarting Firefox fixes it in that case. \n\nOtherwise I haven't seen the error on macOS since this was fixed, definitely not the case where I need to restart my whole computer to fix it.", "id": 14828992, "time": "2020-05-18T17:40:37Z", "raw_text": "I just hit this error on Nightly due to a version mismatch from a Nightly update but I believe that should be handled in a separate bug (maybe even to just give a better error message). Restarting Firefox fixes it in that case. \n\nOtherwise I haven't seen the error on macOS since this was fixed, definitely not the case where I need to restart my whole computer to fix it.", "tags": [], "bug_id": 1615412, "count": 39, "is_private": false, "author": "mozilla+bmo@noorenberghe.ca"}, {"raw_text": "I might have found another exception leading to a broken browser toolbox, bug 1644772.\n\nI'm closing this bug as the ipv6 issue is fixed. Let's reopen new bugs from now as this bug has sailed on 77.", "time": "2020-06-10T15:32:22Z", "author": "poirot.alex@gmail.com", "count": 40, "is_private": false, "tags": [], "bug_id": 1615412, "creation_time": "2020-06-10T15:32:22Z", "attachment_id": null, "creator": "poirot.alex@gmail.com", "id": 14874355, "text": "I might have found another exception leading to a broken browser toolbox, bug 1644772.\n\nI'm closing this bug as the ipv6 issue is fixed. Let's reopen new bugs from now as this bug has sailed on 77."}]}}}