{"bugs": {"631678": {"comments": [{"count": 0, "raw_text": "User-Agent:       Mozilla/5.0 (X11; Linux i686; rv:2.0b7) Gecko/20100101 Firefox/4.0b7\nBuild Identifier: 4.0b7\n\nIf you beginTransaction();, then run multiple executeAsync()s, the later one failing, the callback will be as if it was successful.\n\nReproducible: Always\n\nSteps to Reproduce:\n1.Connect to a sqlite DB\n2.beginTransaction();\n3.executeAsyc(); // is successful\n4.executeAsync(); // fails, but callback is as if successful\n5.commitTransaction();\nActual Results:  \nboth executeAsync()s callback as if successful, however commitTransaction fails\n\nExpected Results:  \nthe 2nd executeAsync()'s callback should be as if failed\n\nHappens on FF 3.6 too.\n\nMultiple executeAsync()'s respecting that there is an open transaction when beginTransction() is called first and not trying to commit it automatically is undocumented and very helpful.  Since it is undocumented however I'd just want to add that it would be best for any fix to this not change that behavior.", "bug_id": 631678, "is_private": false, "tags": [], "time": "2011-02-04T22:32:03Z", "creation_time": "2011-02-04T22:32:03Z", "author": "agilmore@shaw.ca", "id": 5256516, "attachment_id": null, "creator": "agilmore@shaw.ca", "text": "User-Agent:       Mozilla/5.0 (X11; Linux i686; rv:2.0b7) Gecko/20100101 Firefox/4.0b7\nBuild Identifier: 4.0b7\n\nIf you beginTransaction();, then run multiple executeAsync()s, the later one failing, the callback will be as if it was successful.\n\nReproducible: Always\n\nSteps to Reproduce:\n1.Connect to a sqlite DB\n2.beginTransaction();\n3.executeAsyc(); // is successful\n4.executeAsync(); // fails, but callback is as if successful\n5.commitTransaction();\nActual Results:  \nboth executeAsync()s callback as if successful, however commitTransaction fails\n\nExpected Results:  \nthe 2nd executeAsync()'s callback should be as if failed\n\nHappens on FF 3.6 too.\n\nMultiple executeAsync()'s respecting that there is an open transaction when beginTransction() is called first and not trying to commit it automatically is undocumented and very helpful.  Since it is undocumented however I'd just want to add that it would be best for any fix to this not change that behavior."}, {"creation_time": "2011-02-04T22:37:39Z", "text": "Created attachment 509901\nJS file demonstrating bug, creates a sqlite DB in profile\n\nCreates DB in profile.  It does alert('done') as if successful even tho the FK constraint failed, causing the transaction to fail (no INSERTs are made).\n\ncommitTransaction() then also errors.", "attachment_id": 509901, "id": 5256541, "raw_text": "Creates DB in profile.  It does alert('done') as if successful even tho the FK constraint failed, causing the transaction to fail (no INSERTs are made).\n\ncommitTransaction() then also errors.", "tags": [], "is_private": false, "creator": "agilmore@shaw.ca", "author": "agilmore@shaw.ca", "bug_id": 631678, "count": 1, "time": "2011-02-04T22:37:39Z"}]}}, "comments": {}}